name: 🚀 Auto Update README
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # Diário 6h UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Run update script
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sed -i 's/TOKEN = "ghp_.*/TOKEN = "${{ secrets.GITHUB_TOKEN }}"/' update_readme_auto.py
        python update_readme_auto.py
    
    - name: Commit changes
      run: |
        git config user.name "MichaelDouglasCA"
        git config user.email "michaeldouglascruzalves@gmail.com"
        git add README.md
        git diff --staged --quiet || git commit -m "📊 Auto-update README $(date)"
        git push
